import { GraffitiPin, Artist } from './types';

export const mockArtists: Artist[] = [
  {
    id: 1,
    handle: '@banksy',
    bio: 'Anonymous England-based street artist',
    avatar: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    socialLinks: { instagram: 'banksy' },
    notionId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    handle: '@shepard_fairey',
    bio: 'American contemporary artist, activist',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    socialLinks: { instagram: 'obeygiant', website: 'obeygiant.com' },
    notionId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockPins: GraffitiPin[] = [
  {
    id: 1,
    name: 'Girl with Balloon',
    latitude: 40.7589,
    longitude: -73.9851,
    images: [
      'https://images.unsplash.com/photo-1578926288207-01fa5049f2e9?w=800',
      'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800',
    ],
    styleTags: ['stencil', 'political'],
    artistId: 1,
    status: 'active',
    city: 'New York',
    description: 'Iconic stencil artwork depicting a girl reaching for a red heart balloon',
    notionId: null,
    submittedByUserId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: 'Hope Poster',
    latitude: 40.7484,
    longitude: -73.9857,
    images: [
      'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800',
    ],
    styleTags: ['street art', 'political'],
    artistId: 2,
    status: 'active',
    city: 'New York',
    description: 'Stylized portrait in red, white, and blue',
    notionId: null,
    submittedByUserId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: 'Colorful Mural',
    latitude: 40.7614,
    longitude: -73.9776,
    images: [
      'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800',
    ],
    styleTags: ['mural', 'abstract'],
    artistId: null,
    status: 'active',
    city: 'New York',
    description: 'Vibrant abstract mural in Manhattan',
    notionId: null,
    submittedByUserId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: 'Urban Expression',
    latitude: 40.7282,
    longitude: -73.9942,
    images: [
      'https://images.unsplash.com/photo-1578926288207-01fa5049f2e9?w=800',
    ],
    styleTags: ['graffiti', 'letters'],
    artistId: null,
    status: 'buffed',
    city: 'New York',
    description: 'Bold letter piece in downtown area (removed)',
    notionId: null,
    submittedByUserId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
